#! /bin/sh

sxhkd &
pkill polybar
~/.config/polybar/launch.sh
picom &
lightscreen &
kitty &
ibus-daemon &
nitrogen --set-scaled /mnt/sda5/owo.jpg

bspc monitor -d terminal web discord osu V VI VII VIII IX X

bspc config border_width         0 
bspc config window_gap           0 

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a polybar border=off manage=off
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Google-chrome desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Lightscreen desktop='^9'
bspc rule -a discord desktop='^3'
bspc rule -a Spotify desktop='^6' state=pseudo_tiled
