#! /bin/sh

pkill polybar
~/.config/polybar/launch.sh &
dunst &
picom &
kitty &
nitrogen --restrore &
xsetroot -cursor_name left_ptr

bspc monitor -d terminal editor web random spotify

bspc config border_width         2
bspc config normal_border_color  "#6272a4"
bspc config focused_border_color  "#8be9fd"
bspc config window_gap           10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a polybar border=off manage=off
bspc rule -a Google-chrome desktop='^2'
bspc rule -a Screenkey manage=off
bspc rule -a Spotify desktop='^4'
